name: Daily puzzle
on:
  schedule:
    # at midnight
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Copy puzzles to production
        env:
          HEALTHCHECK_URL: {{ secrets.HEALTHCHECK_URL }}
        run: |
          python newPuzzle.py
      - name: Commit report # this will trigger a redeploy
        run: |
          git config --global user.name 'Kiru'
          git config --global user.email 'kiru@users.noreply.github.com'
          git add nextPuzzles/*
          git commit -am "New puzzle via GH action"
          git push

